baseURL = "https://damianfernandez.mx/"
languageCode = "es-mx"
theme = "hyde"
title = "D•F"
[params]
description = "blog"
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = "theme-base-08"
