baseURL = "https://damianfernandez.mx/"
languageCode = "es-mx"
theme = "hyde"
title = "Damián•Fernández"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = "theme-base-08"
